Repository iamgoodbytes/dev5-portfolios-2023, pull requests merged in 2023-12, with the labels that each got.

#104 Feat(evivermeeren.md): add labo 6 links + GIF
  evivermeeren.md
Labels: ready to check

#107 Update Labo2
  MauroVanderFlaes.md
Labels: update required, ready to check

#110 feat: add labo 6
  yadinaMoreira.md
Labels: ready to check

#111 feat(lab 6): add lab 6
  tiboMertens.md
Labels: ready to check

#117 feat: add lab6 + link
  yannick_vandenbrande.md
Labels: update required

#108 feat: add lab4 to portfolio
  GlennVinck.md
Labels: update required

#103 feat: Add Lab4 links
  brittadam.md
Labels: update required

#92 feat: add Lab 3 API according to the temp it reccomends a skin to use…
  tjerk_symens.md
Labels: update required

#118 feat: add lab 4 with mongodb
  LindsayPeeters.md
Labels: update required

#127 feat: add link labo 5
  zahraJanssens.md
Labels: ready to check

#106 add(lab2): add link
  wolf_ver_elst.md
Labels: update required, help wanted

#113 Feat: add lab 5
  jarobrichau.md
Labels: update required

#125 feat: add Lab2 to Bramcolleman.md file
  BramColleman.md
Labels: update required

#133 feat: add labo5 links
  jarne_simons.md
Labels: live demo missing

#135 Feat:Add Lab2
  Tibo_vermeire.md
Labels: ready to check

#137 Feat: add lab 6
  jarobrichau.md
Labels: ready to check

#138 Add: labo 5 links
  zegherbaerts.md
Labels: update required

#139 feat: add link labo 6
  zahraJanssens.md
Labels: ready to check

#142 feat: add lab 6
  GlennVinck.md
Labels: ready to check

#144 feat: add lab 4 link & fix in lab 5
  wolf_ver_elst.md
Labels: update required, ready to check

#145 Feat: add Labo 5
  MauroVanderFlaes.md
Labels: update required, ready to check

#146 Add lab 2-6 to BrendVandenEynde.md
  BrendVandenEynde.md
Labels: update required, ready to check
