Repository iamgoodbytes/dev5-portfolios-2023, pull requests merged in 2023-10, with the labels that each got.

#49 feat: add labo 2
  yadinaMoreira.md
Labels: update required

#62 feat(lab3): add lab3
  tiboMertens.md
Labels: update required

#39 fix: github link
  tjerk_symens.md
Labels: live demo missing

#67 Feat: add jarobrichau.md
  jarobrichau.md
Labels: update required

#71 feat: add labo2 link
  zahraJanssens.md
Labels: ready to check

#72 feat: add labo2 Islands
  jarne_simons.md
Labels: ready to check

#76 feat: add labo 4
  yadinaMoreira.md
Labels: ready to check

#77 feat(evivermeeren.md): added links to labo 4
  evivermeeren.md
Labels: ready to check

#78 feat: add lab3 links
  yannick_vandenbrande.md
Labels: ready to check

#81 Labo3juist
  yadinaMoreira.md
Labels: ready to check

#82 feat: add Labo4 link and codesandbox link
  ArneSamson.md
Labels: ready to check
